# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('alternative', models.CharField(max_length=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra.Dish')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
